baseURL: "https://kkroesch.github.io/Polygraf/"
languageCode: "de"
title: "µMezura-8 Dokumentation"

markup:
  goldmark:
    parser:
      attribute:
        block: true # ermöglicht {.epigraph} u. ä.
    renderer:
      unsafe: true # erlaubt Inline-HTML wie <figure>
  highlight:
    style: borland
    lineNos: true
    noClasses: false # nutzt chroma.css für Styling
